# This file is used to configure the Flame Workspace.
# This file is generated automatically and should not be modified manually.

project_name: template
organization: com.example.template

# The name of the initial scene class.
initial_scene: Scene1