name: template
resolution: workspace
description: "An awesome game created with Flame and Flame Workspace."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.38.2
  flame_workspace_runtime:
    path: '../flame_workspace_runtime'

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
