/// This file is generated by Flame Workspace.
/// Do not edit it manually.

import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';

import 'package:template/components/my_component.dart';

void setPropertyValue(
  String className,
  dynamic cls,
  String propertyName,
  dynamic value,
) {
  if (className != 'MyComponent') {
    throw ArgumentError.value(className, 'Class not found');
  }

  final component = cls as MyComponent;
  switch (propertyName) {
    case 'position':
      component.position = value as Vector2;
      break;
    case 'size':
      component.size = value as Vector2;
      break;
    case 'angle':
      component.angle = value as double;
      break;
    case 'priority':
      component.priority = value as int;
      break;
    default:
      throw ArgumentError.value(propertyName, 'Property not found');
  }
}
