// This file is generated by Flame Workspace.
// Do not edit it manually.

import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';
import 'package:template/scenes/level_one/level_one.dart';

void setScene(String sceneName) {
  switch (sceneName) {
    case "LevelOne":
      FlameWorkspaceCore.instance.currentScene = LevelOne();
      break;
    default:
      throw ArgumentError.value(sceneName, 'Scene not found');
  }
}

void setInitialScene() {
  setScene('LevelOne');
}
