/// This file is generated by Flame Workspace.
/// Do not edit it manually.

// ignore_for_file: unused_import
import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';
import 'package:template/scenes/level_one/level_one_script.dart';

void setScene(String sceneName) {
  switch (sceneName) {
    case r'$SceneLevelOne':
      FlameWorkspaceCore.instance.currentScene = SceneLevelOne();
      break;
    default:
      throw ArgumentError.value(sceneName, 'Scene not found');
  }
}
