/// This file is generated by Flame Workspace.
/// Do not edit it manually.

// ignore_for_file: unused_import
import 'package:flame_workspace_core/flame_workspace_core.dart';

void setScene(String sceneName) {
  switch (sceneName) {
    default:
      throw ArgumentError.value(sceneName, 'Scene not found');
  }
}
