name: flame_workspace_communication_bridge
description: "Flame Workspace Communication Bridge"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  flame_workspace_protocol:
    path: ../flame_workspace_protocol
  vm_service: ^15.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
