/// This file is generated by Flame Workspace.
/// Do not edit it manually.

import 'package:flame/components.dart';
import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';

import 'package:template/components/my_component.dart';

Future<void> populateLevelOneWorkspaceScene(World world) async {
  if (world is FlameScene) {
    world.backgroundColor = Color(0xFF000000);
  }
  final component0 = MyComponent(
    key: FlameKey('scene:template:level-one:component:my-component'),
  );
  (component0 as PositionComponent)
    ..position = Vector2(64.0, 64.0)
    ..size = Vector2(128.0, 128.0)
    ..scale = Vector2(1.0, 1.0)
    ..angle = 0.0
    ..anchor = Anchor.topLeft
    ..priority = 0;
  world.add(component0);
}
