// This file is generated by Flame Workspace.
// Do not edit it manually.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i1;
import 'dart:ui' as _i4;

import 'package:flame/components.dart' as _i2;
import 'package:flame_workspace_runtime/flame_workspace_runtime.dart' as _i3;
import 'package:template/components/my_component.dart' as _i5;

_i1.Future<void> populateLevelOneWorkspaceScene(_i2.World world) async {
  (world as _i3.FlameScene).backgroundColor = const _i4.Color(4278190080);
  final component0 = _i5.MyComponent(
    key: _i3.FlameKey('scene:template:level-one:component:my-component'),
  );
  (component0 as _i2.PositionComponent)
    ..position = _i2.Vector2(64.0, 64.0)
    ..size = _i2.Vector2(128.0, 128.0)
    ..scale = _i2.Vector2(1.0, 1.0)
    ..angle = 0.0
    ..anchor = _i2.Anchor.topLeft
    ..priority = 0;
  world.add(component0);
}
