name: flame_workspace_core
description: Necessary code to make a Flame app work with the IDE
version: 0.0.1
resolution: workspace
homepage:

publish_to: "none"

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  flame_workspace_protocol:
    path: ../flame_workspace_protocol
  flame_workspace_runtime:
    path: ../flame_workspace_runtime

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
