name: flame_workspace_core
description: Necessary code to make a Flame app work with the IDE
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0-41.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flame: 1.9.1
  flame_audio: 2.1.1
  flame_forge2d: 0.15.0+1
  flame_isolate: 0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
