name: flame_workspace_core
description: Necessary code to make a Flame app work with the IDE
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0-41.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
