import 'dart:convert';
import 'dart:io';

import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;

import '../parser/component_capabilities.dart';
import '../parser/writer.dart';
import '../project/objects/component.dart';
import '../project/project.dart';
import 'workspace_dart_emitter.dart';

/// Generates runtime property dispatchers for the discovered component API.
class PropertiesGenerator {
  static const _transformProperties = {
    'position',
    'size',
    'scale',
    'angle',
    'nativeAngle',
    'anchor',
    'priority',
  };

  static bool _containsPrivateType(String type) =>
      RegExp(r'(^|[^A-Za-z0-9])_[A-Za-z]').hasMatch(type);
  PropertiesGenerator._();

  static String generateForFlameComponent(FlameComponentObject component) {
    final method = _componentSetter(component, component.name);
    if (method == null) return '';
    return Writer.formatDartString(
      WorkspaceDartEmitter.emit(
        Library((builder) => builder..body.add(method)),
      ),
    );
  }

  static Future<void> writeForComponents(
    Iterable<FlameComponentObject> components,
    FlameProject project,
  ) async {
    final componentList = components.toList()
      ..sort((first, second) => first.name.compareTo(second.name));
    final setters = <FlameComponentObject, Method>{};
    for (final component in componentList) {
      final setter = _componentSetter(component, component.name);
      if (setter != null) setters[component] = setter;
    }
    final projectImports = <String>{
      for (final component in componentList)
        if (component.filePath case final filePath?)
          _projectImportUri(filePath, project),
    }.toList()..sort();
    final needsUnawaited = setters.keys.any(
      (component) => component.name == 'TextBoxComponent',
    );

    final library = Library(
      (builder) => builder
        ..comments.add('This file is generated by Flame Workspace.')
        ..comments.add('Do not edit it manually.')
        ..comments.add(
          'ignore_for_file: unused_import, unnecessary_import, unnecessary_this',
        )
        ..directives.add(Directive.import(WorkspaceDartEmitter.runtime))
        ..directives.addAll([
          if (needsUnawaited) Directive.import('dart:async'),
          for (final uri in projectImports) Directive.import(uri),
        ])
        ..body.add(_dispatcher(setters.keys))
        ..body.addAll(setters.values),
    );

    final file = File(
      path.join(
        project.location.path,
        'lib',
        generatedFilesDirectory,
        'properties.dart',
      ),
    );
    if (!(await file.exists())) file.createSync(recursive: true);
    await Writer.writeFormatted(file, WorkspaceDartEmitter.emit(library));
  }

  static Method? _componentSetter(
    FlameComponentObject component,
    String className,
  ) {
    final properties =
        component.writableProperties
            .where(
              (property) =>
                  property.typeAccessible &&
                  (component.data['api'] != true ||
                      ComponentSupportMatrix.supportsRuntimeProperty(
                        component.name,
                        property.name,
                      )) &&
                  !_transformProperties.contains(property.name) &&
                  !_containsPrivateType(property.type) &&
                  !property.type.startsWith('void Function'),
            )
            .toList()
          ..sort((first, second) => first.name.compareTo(second.name));
    if (properties.isEmpty) return null;

    // code_builder intentionally has no switch-statement specification. Keep
    // this control-flow fragment local while all declarations and imports are
    // built structurally above.
    final cases = StringBuffer();
    for (final property in properties) {
      final type = _castType(property.type);
      cases
        ..writeln('case ${jsonEncode(property.name)}:')
        ..writeln('  cls.${property.name} = value as $type;');
      if (className == 'TextBoxComponent' && property.name == 'align') {
        cases.writeln('  unawaited(cls.redraw());');
      }
      cases.writeln('  break;');
    }
    cases
      ..writeln('default:')
      ..writeln(
        "  throw ArgumentError.value(propertyName, 'Property not found');",
      );

    return Method(
      (builder) => builder
        ..name = 'setPropertyValue$className'
        ..returns = refer('void')
        ..requiredParameters.addAll([
          Parameter(
            (builder) => builder
              ..name = 'cls'
              ..type = refer(className),
          ),
          Parameter(
            (builder) => builder
              ..name = 'propertyName'
              ..type = refer('String'),
          ),
          Parameter(
            (builder) => builder
              ..name = 'value'
              ..type = refer('dynamic'),
          ),
        ])
        ..body = Code('switch (propertyName) {\n$cases}'),
    );
  }

  static Method _dispatcher(Iterable<FlameComponentObject> components) {
    final ordered = components.toList()
      ..sort((first, second) => first.name.compareTo(second.name));
    // See [_componentSetter] for why this switch remains a compact Code node.
    final cases = StringBuffer();
    for (final component in ordered) {
      cases
        ..writeln('case ${jsonEncode(component.name)}:')
        ..writeln(
          '  setPropertyValue${component.name}(cls as ${component.name}, propertyName, value);',
        )
        ..writeln('  break;');
    }
    cases
      ..writeln('default:')
      ..writeln("  throw ArgumentError.value(className, 'Class not found');");
    return Method(
      (builder) => builder
        ..name = 'setPropertyValue'
        ..returns = refer('void')
        ..requiredParameters.addAll([
          Parameter(
            (builder) => builder
              ..name = 'className'
              ..type = refer('String'),
          ),
          Parameter(
            (builder) => builder
              ..name = 'cls'
              ..type = refer('dynamic'),
          ),
          Parameter(
            (builder) => builder
              ..name = 'propertyName'
              ..type = refer('String'),
          ),
          Parameter(
            (builder) => builder
              ..name = 'value'
              ..type = refer('dynamic'),
          ),
        ])
        ..body = Code('switch (className) {\n$cases}'),
    );
  }

  static String _castType(String type) {
    final normalized = type.replaceAll('?', '');
    return normalized.length == 1 ? 'dynamic' : normalized;
  }

  static String _projectImportUri(String filePath, FlameProject project) {
    final libPath = path.join(project.location.path, 'lib');
    final relative = path.relative(filePath, from: libPath);
    if (relative == '..' || relative.startsWith('..${path.separator}')) {
      throw FormatException(
        'Component source must be inside the project lib directory: $filePath',
      );
    }
    return 'package:${project.name}/${relative.replaceAll(path.separator, '/')}';
  }
}
