import 'dart:convert';
import 'dart:io';

import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;

import '../model/semantic_model.dart';
import '../parser/writer.dart';
import '../project/project.dart';
import 'scene_naming.dart';
import 'workspace_dart_emitter.dart';

/// Generates the global runtime scene dispatcher from the semantic scene set.
class SceneDispatcherGenerator {
  const SceneDispatcherGenerator._();

  static String generate(
    Iterable<SceneDefinition> scenes,
    FlameProject project,
  ) {
    final orderedScenes = scenes.toList()
      ..sort((first, second) => first.name.compareTo(second.name));
    if (orderedScenes.isEmpty) {
      throw StateError('A project must retain at least one scene.');
    }
    final names = <String>{};
    final runtimeTypes = <SceneDefinition, String>{};
    final imports = <String>{WorkspaceDartEmitter.runtime};

    for (final scene in orderedScenes) {
      if (!names.add(scene.name)) {
        throw FormatException('Duplicate scene name: ${scene.name}');
      }
      final sourcePath = _runtimeSourcePath(scene, project);
      imports.add(_importFor(sourcePath, project));
      final runtimeType =
          scene.runtimeClassName ?? _runtimeClassName(scene, sourcePath);
      _identifier(runtimeType, 'runtime class for scene ${scene.id}');
      runtimeTypes[scene] = runtimeType;
    }

    // code_builder has no switch-statement node. This is limited to dispatcher
    // control flow; imports, function declarations, literals, and the initial
    // scene invocation remain structured code_builder nodes.
    final cases = StringBuffer();
    for (final scene in orderedScenes) {
      cases
        ..writeln('case ${jsonEncode(scene.name)}:')
        ..writeln(
          '  FlameWorkspaceCore.instance.currentScene = ${runtimeTypes[scene]}();',
        )
        ..writeln('  break;');
    }
    cases
      ..writeln('default:')
      ..writeln("  throw ArgumentError.value(sceneName, 'Scene not found');");

    final initialScene = names.contains(project.initialScene)
        ? project.initialScene
        : orderedScenes.first.name;
    return Writer.formatDartString(
      WorkspaceDartEmitter.emit(
        Library(
          (builder) => builder
            ..comments.add('This file is generated by Flame Workspace.')
            ..comments.add('Do not edit it manually.')
            ..directives.addAll([
              for (final uri in imports.toList()..sort()) Directive.import(uri),
            ])
            ..body.addAll([
              Method(
                (builder) => builder
                  ..name = 'setScene'
                  ..returns = refer('void')
                  ..requiredParameters.add(
                    Parameter(
                      (builder) => builder
                        ..name = 'sceneName'
                        ..type = refer('String'),
                    ),
                  )
                  ..body = Code('switch (sceneName) {\n$cases}'),
              ),
              Method(
                (builder) => builder
                  ..name = 'setInitialScene'
                  ..returns = refer('void')
                  ..body = Block.of([
                    refer('setScene')
                        .call([literalString(initialScene)])
                        .statement,
                  ]),
              ),
            ]),
        ),
      ),
    );
  }

  static File fileForScenes(FlameProject project) => File(
    path.join(project.location.path, 'lib', '.generated', 'scenes.dart'),
  );

  static Future<File> writeForScenes(
    Iterable<SceneDefinition> scenes,
    FlameProject project,
  ) async {
    final file = fileForScenes(project);
    await file.parent.create(recursive: true);
    await Writer.writeFormatted(file, generate(scenes, project));
    return file;
  }

  static String _runtimeSourcePath(
    SceneDefinition scene,
    FlameProject project,
  ) {
    final runtimeSourcePath = scene.runtimeSourcePath;
    if (runtimeSourcePath != null) return runtimeSourcePath;

    final sourcePath =
        scene.sourcePath ??
        path.join(
          project.location.path,
          'lib',
          'scenes',
          WorkspaceSceneNaming.fileName(scene.name),
          '${WorkspaceSceneNaming.fileName(scene.name)}.dart',
        );
    final scriptPath = path.join(
      path.dirname(sourcePath),
      WorkspaceSceneNaming.scriptFileName(scene.name),
    );
    return File(scriptPath).existsSync() ? scriptPath : sourcePath;
  }

  static String _runtimeClassName(SceneDefinition scene, String sourcePath) {
    return path.basename(sourcePath) ==
            WorkspaceSceneNaming.scriptFileName(scene.name)
        ? WorkspaceSceneNaming.behaviorClassName(scene.name)
        : WorkspaceSceneNaming.baseClassName(scene.name);
  }

  static String _importFor(String sourcePath, FlameProject project) {
    final libDirectory = path.join(project.location.path, 'lib');
    final resolvedSourcePath = path.isAbsolute(sourcePath)
        ? sourcePath
        : path.join(project.location.path, sourcePath);
    final relativePath = path.relative(resolvedSourcePath, from: libDirectory);
    if (relativePath == '..' ||
        relativePath.startsWith('..${path.separator}')) {
      throw FormatException(
        'Scene runtime source must be inside the project lib directory: $sourcePath',
      );
    }
    return 'package:${project.name}/${relativePath.replaceAll(path.separator, '/')}';
  }

  static void _identifier(String value, String context) {
    if (!RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(value)) {
      throw FormatException('Invalid Dart identifier "$value" for $context.');
    }
  }
}
