import 'package:recase/recase.dart';

import '../generators/scene_naming.dart';

String main$dart(String gameName) =>
    '''import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';

import '.generated/properties.dart';
import '.generated/scenes.dart';
import 'game.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final game = $gameName();
  FlameWorkspaceCore.instance.setPropertyValue = setPropertyValue;
  FlameWorkspaceCore.instance.setScene = setScene;
  await FlameWorkspaceCore.ensureInitialized(game);

  runApp(GameWidget<$gameName>(game: game));
}''';

String game$dart(String gameName) {
  return '''import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';

import '.generated/scenes.dart';

class $gameName extends FlameGame {
  @override
  Future<void> onLoad() async {
    setInitialScene();
    await super.onLoad();

    camera = CameraComponent(world: world);
    camera.viewfinder.anchor = Anchor.topLeft;
    add(camera);
  }
}''';
}

String scene$dart(String sceneName) {
  final name = WorkspaceSceneNaming.normalize(sceneName);
  final baseClassName = WorkspaceSceneNaming.baseClassName(name);
  final fileName = WorkspaceSceneNaming.fileName(name);
  return '''import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';

import '../../.generated/scenes/$fileName.workspace.dart';

part '${WorkspaceSceneNaming.scriptFileName(name)}';

@protected
class $baseClassName extends FlameScene {
  $baseClassName()
      : super(
          sceneName: '$name',
          backgroundColor: const Color(0xFF000000),
        );

  @override
  Future<void> onLoad() async {
    await super.onLoad();
    await populate${name}WorkspaceScene(this);
  }
}''';
}

String sceneScript$dart(String sceneName) {
  final name = WorkspaceSceneNaming.normalize(sceneName);
  final className = WorkspaceSceneNaming.behaviorClassName(name);
  final baseClassName = WorkspaceSceneNaming.baseClassName(name);
  final fileName = WorkspaceSceneNaming.fileName(name);
  return '''part of '$fileName.dart';

class $className extends $baseClassName {}''';
}

String component$dart(String componentName) {
  final className = componentName.pascalCase;
  return '''import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';

class $className extends PositionComponent {
  $className({super.key, super.position, super.size});

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    canvas.drawRect(
      size.toRect(),
      Paint()..color = const Color(0xFFFFB431),
    );
  }
}''';
}

String properties$dart(String projectName, String componentName) {
  final className = componentName.pascalCase;
  return '''/// This file is generated by Flame Workspace.
/// Do not edit it manually.

import 'package:flame_workspace_runtime/flame_workspace_runtime.dart';

import 'package:$projectName/components/${componentName.snakeCase}.dart';

void setPropertyValue(
  String className,
  dynamic cls,
  String propertyName,
  dynamic value,
) {
  if (className != '$className') {
    throw ArgumentError.value(className, 'Class not found');
  }

  final component = cls as $className;
  switch (propertyName) {
    case 'position':
      component.position = value as Vector2;
      break;
    case 'size':
      component.size = value as Vector2;
      break;
    case 'angle':
      component.angle = value as double;
      break;
    case 'priority':
      component.priority = value as int;
      break;
    default:
      throw ArgumentError.value(propertyName, 'Property not found');
  }
}''';
}

String pubspec$yaml(
  String projectName,
  String description, {
  String? runtimeDependencyPath,
}) {
  final runtimeDependency = runtimeDependencyPath == null
      ? '''git:
      url: https://github.com/bdlukaa/flame_workspace
      path: flame_workspace_runtime/'''
      : "path: '${runtimeDependencyPath.replaceAll("'", "''")}'";

  return '''name: ${projectName.snakeCase}
description: "$description"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.38.2
  flame_workspace_runtime:
    $runtimeDependency

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
''';
}

String smokeTest$dart(String projectName, String gameName) =>
    '''import 'package:flame/game.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:$projectName/game.dart';

void main() {
  test('the generated game can be constructed', () {
    expect($gameName(), isA<FlameGame>());
  });
}''';

String flameConfiguration$yaml({
  required String projectName,
  required String organization,
  required String initialScene,
}) =>
    '''# This file is used to configure Flame Workspace.
# This file is generated automatically and should not be modified manually.

project_name: ${projectName.snakeCase}
organization: $organization
initial_scene: $initialScene
''';
