name: flame_workspace
description: "Create 2D games with Flame and Flutter!"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.0-41.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flame
  flame: 1.9.1

  # Project indexer/analyzer
  analyzer: 5.13.0
  dartdoc_json: ^0.2.0
  code_builder: ^4.7.0
  source_gen: ^1.4.0
  http: ^1.1.0

  # External functionality
  file_picker: ^5.5.0
  yaml: ^3.1.2
  path: ^1.8.3

  # Windowing
  window_manager: ^0.3.7
  flutter_native_view: ^0.0.2
  win32: ^5.0.9
  ffi: ^2.1.0
  process_run: ^0.13.1

  # UI
  flutter_colorpicker: ^1.0.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
