name: flame_workspace
description: "Create 2D games with Flame and Flutter!"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter

  # Flame
  flame: ^1.38.2

  # Project indexer/analyzer
  analyzer: ^10.2.0
  http: ^1.6.0
  recase: ^4.1.0
  dart_style: ^3.1.7

  # External functionality
  file_picker: ^8.0.7
  yaml: ^3.1.4
  path: ^1.9.1

  # Windowing
  window_manager: ^0.5.2
  flutter_native_view: ^0.0.2
  win32: ^5.0.9
  ffi: ^2.2.0
  process_run: ^0.13.1

  # UI
  flutter_colorpicker: ^1.1.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0

  # Connection
  flame_workspace_protocol:
    path: ../flame_workspace_protocol
  flame_workspace_runtime:
    path: ../flame_workspace_runtime
  web_socket_channel: ^2.4.0
  flame_workspace_communication_bridge:
    path: ../flame_workspace_communication_bridge

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
